### ISSUE TITLE
Ultimate TODO list

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/native#156]
### MAJOR ONES
-  [x] issue with delete event #190 
-  [x] calendar doesn't display just created events
-  [x] after the event just been created the input fields are not cleared up
-  [x] on feed screen hosting button doesn't filter properly 
-  [x] update the mailgun with new settings - on server side
-  [x] logout issue
-  [x] feed rendering duplication #179 
-  [x] redirection issue from Feed to event #183 
-  [x] issue with photo #177 
-  [x] display message on unrecognised code 
-  [x] fix styling error issue on ```auth```
-  [x] device issue #176 
-  [x] calendar
-  [x] whatapp message #126  // sometimes appears as not converted string
-  [x] vote count for an event poll
-  [x] clear persist state on logout
-  [x] add server error on ```sign up``` form #90, #47, #4  also in general errors #144  
-  [x] redirection to Navbar if authenticated #121
-  [x] delete event feature 
-  [x] issue with date conversion ? #127 
-  [x] from Profile page add navigation to Upload photo for changing the user photo 
-  [x] reset `user` state in AsyncStorage on logout
-  [x] Create event: what and where can be left blank (value will be string `TBC`)

### STYLING/LAYOUT
-  [x] login form improvement #157 
-  [x] upload photo layout #112 

### ENHANCEMENTS
-  [ ] abstract navbar icon into the function #24
