### ISSUE TITLE
TODO issues

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/native#288]
- [ ] calendar issues #259, #249
- [ ] after edit event - changes not reflected on event 
- [ ] option to add TBC ion time when creating event #242, #201 
- [ ] don't pass error object to reducer #247, #222
- [ ] autocomplete to change it to everywhere #240, #282
- [ ] feed enhancements #208, #203, #249
