### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/native#6]
_From @heron2014 on January 6, 2017 11:34_

- [x] auth (save token, redirection to private resources)
- [x] auth (check for existence of token, redirect user straight to Feed page) #48 
- [x] extra field for event code #108 
- [x] refactor profile page reducers and actions plus styling
- [x] add fake avatar for the user
- [x] refactor reducers and actions for Feed screen
- [x] refactor reducers and actions for Calendar screen
- [x] refactor reducers and actions for Event screen **(in progress #57)**
- [x] refactor reducers and actions for Poll screen for invitees **(in progress #57 )**
- [x] refactor reducers and actions for ConfirmEvent screen for invitees **(in progress #57)**
- [x] refactor reducers and actions for Poll screen for host **(in progress #57)**
- [x] refactor reducers and actions for ConfirmEvent screen for host **(in progress #57)**
- [x] refactor reducers and actions delete the event
- [x] summary page for creating event
- [x] summary page reducers and actions
- [x] upload profile photo page #61 
- [x] forgot password on login page #63 
- [x] form page for reseting password #63
- [x] create invite more friends feature
- [x] sockets #110 

_Copied from original issue: DRDD2016/sparkn2#64_
